version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./data/html:/usr/share/nginx/html
  app:
    build: ./app
    ports:
      - "9000:9000"
    volumes:
      - ./data/html:/usr/share/nginx/html
