version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/backend.conf:/etc/nginx/conf.d/backend.conf
      - ./backend/php-fpm.conf:/etc/nginx/conf.d/php-fpm.conf
      - ./backend/html:/usr/share/nginx/html
      - phpsocket:/var/run/php-fpm

  php:
    build: ./php
    ports:
      - "9000:9000"
    volumes:
      - ./backend/html:/usr/share/nginx/html
      - ./php/php.ini:/etc/php.ini
      - ./php/www.conf:/etc/php-fpm.d/www.conf
      - ./php/10-opcache.ini:/etc/php.d/10-opcache.ini
      - phpsocket:/var/run/php-fpm

volumes:
  phpsocket:
