version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./data/html:/var/www/html
  php:
    build: ./php
    env_file: .env
    environment:
      DATABASE_HOST: mysql
    depends_on:
      - mysql
    volumes:
      - ./data/html:/var/www/html
  mysql:
    image: mysql:5.7.23
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/initial.sql:/docker-entrypoint-initdb.d/initial.sql

volumes:
  mysql-data:
